package io.github.kabirnayeem99.vindecoder.src

@JvmSynthetic
internal val manufacturers = mapOf(
    "AAV" to "Volkswagen",
    "AC5" to "Hyundai",
    "ADD" to "Hyundai",
    "AFA" to "Ford",
    "AHT" to "Toyota",
    "JA3" to "Mitsubishi",
    "JA4" to "Mitsubishi",
    "JA" to "Isuzu",
    "JD" to "Daihatsu",
    "JF" to "Fuji Heavy Industries (Subaru)",
    "JH" to "Honda",
    "JK" to "Kawasaki (motorcycles)",
    "JL5" to "Mitsubishi Fuso",
    "JMB" to "Mitsubishi Motors",
    "JMY" to "Mitsubishi Motors",
    "JMZ" to "Mazda",
    "JN" to "Nissan",
    "JS" to "Suzuki",
    "JS0" to "Suzuki",
    "JS1" to "Suzuki",
    "JS8" to "Suzuki",
    "JT" to "Toyota",
    "JY" to "Yamaha (motorcycles)",
    "KL" to "Daewoo General Motors",
    "KM" to "Hyundai",
    "KMY" to "Daelim (motorcycles)",
    "KM1" to "Hyosung (motorcycles)",
    "KN" to "Kia",
    "KNM" to "Renault Samsung",
    "KPA" to "SsangYong",
    "KPT" to "SsangYong",
    "LAE" to "Jinan Qingqi Motorcycle",
    "LAN" to "Changzhou Yamasaki Motorcycle",
    "LBB" to "Zhejiang Qianjiang Motorcycle (Keeway/Generic)",
    "LBE" to "Beijing Hyundai",
    "LBM" to "Zongshen Piaggio",
    "LBP" to "Chongqing Jianshe Yamaha (motorcycles)",
    "LB2" to "Geely Motorcycles",
    "LCE" to "Hangzhou Chunfeng Motorcycles (CFMOTO)",
    "LDC" to "Dong Feng Peugeot Citroen (DPCA)",
    "LDD" to "Dandong Huanghai Automobile",
    "LDN" to "SouEast Motor",
    "LDY" to "Zhongtong Coach",
    "LET" to "Jiangling-Isuzu Motors",
    "LE4" to "Beijing Benz",
    "LFB" to "FAW (busses)",
    "LFG" to "Taizhou Chuanl Motorcycle Manufacturing",
    "LFP" to "FAW (passenger vehicles)",
    "LFT" to "FAW (trailers)",
    "LFV" to "FAW-Volkswagen",
    "LFW" to "FAW JieFang",
    "LFY" to "Changshu Light Motorcycle Factory",
    "LGB" to "Dong Feng (DFM)",
    "LGH" to "Qoros (formerly Dong Feng (DFM))",
    "LGX" to "BYD Auto",
    "LHB" to "Beijing Automotive Industry Holding",
    "LH1" to "FAW-Haima",
    "LJC" to "JAC",
    "LJ1" to "JAC",
    "LKL" to "Suzhou King Long",
    "LL6" to "Hunan Changfeng Manufacture Joint-Stock",
    "LL8" to "Linhai (ATV)",
    "LMC" to "Suzuki Hong Kong (motorcycles)",
    "LPR" to "Yamaha Hong Kong (motorcycles)",
    "LSG" to "SAIC General Motors",
    "LSJ" to "SAIC MG",
    "LSV" to "SAIC Volkswagen",
    "LSY" to "Brilliance Zhonghua",
    "LTV" to "Toyota Tian Jin",
    "LUC" to "Guangqi Honda",
    "LVS" to "Ford Chang An",
    "LVV" to "Chery",
    "LVZ" to "Dong Feng Sokon Motor Company (DFSK)",
    "LZM" to "MAN",
    "LZE" to "Isuzu Guangzhou",
    "LZG" to "Shaanxi Automobile Group",
    "LZP" to "Zhongshan Guochi Motorcycle (Baotian)",
    "LZY" to "Yutong Zhengzhou",
    "LZZ" to "Chongqing Shuangzing Mech & Elec (Howo)",
    "L4B" to "Xingyue Group (motorcycles)",
    "L5C" to "KangDi (ATV)",
    "L5K" to "Zhejiang Yongkang Easy Vehicle",
    "L5N" to "Zhejiang Taotao (ATV & motorcycles)",
    "L5Y" to "Merato Motorcycle Taizhou Zhongneng",
    "L85" to "Zhejiang Yongkang Huabao Electric Appliance",
    "L8X" to "Zhejiang Summit Huawin Motorcycle",
    "MAB" to "Mahindra & Mahindra",
    "MAC" to "Mahindra & Mahindra",
    "MAJ" to "Ford",
    "MAK" to "Honda Siel Cars",
    "MAL" to "Hyundai",
    "MAT" to "Tata Motors",
    "MA1" to "Mahindra & Mahindra",
    "MA3" to "Suzuki (Maruti)",
    "MA6" to "GM",
    "MA7" to "Mitsubishi (formerly Honda)",
    "MBH" to "Suzuki (Maruti)",
    "MBJ" to "Toyota",
    "MBR" to "Mercedes-Benz",
    "MB1" to "Ashok Leyland",
    "MCA" to "Fiat",
    "MCB" to "GM",
    "MC2" to "Volvo Eicher commercial vehicles limited.",
    "MDH" to "Nissan",
    "MD2" to "Bajaj Auto",
    "MD9" to "Shuttle Cars",
    "MEE" to "Renault",
    "MEX" to "Volkswagen",
    "MHF" to "Toyota",
    "MHR" to "Honda",
    "MLC" to "Suzuki",
    "MLH" to "Honda",
    "MMB" to "Mitsubishi",
    "MMC" to "Mitsubishi",
    "MMM" to "Chevrolet",
    "MMS" to "Suzuki",
    "MMT" to "Mitsubishi",
    "MM8" to "Mazda",
    "MNB" to "Ford",
    "MNT" to "Nissan",
    "MPA" to "Isuzu",
    "MP1" to "Isuzu",
    "MRH" to "Honda",
    "MR0" to "Toyota",
    "MS0" to "KIA",
    "MS3" to "Suzuki Motor Co., Ltd.",
    "NLA" to "Honda",
    "NLE" to "Mercedes-Benz Truck",
    "NLH" to "Hyundai Assan",
    "NLT" to "TEMSA",
    "NMB" to "Mercedes-Benz Buses",
    "NMC" to "BMC",
    "NM0" to "Ford",
    "NM4" to "Tofaş",
    "NMT" to "Toyota",
    "NNA" to "Isuzu",
    "PE1" to "Ford",
    "PE3" to "Mazda",
    "PL1" to "Proton",
    "PNA" to "NAZA (Peugeot)",
    "RA1" to "Steyr Trucks International FZE",
    "RFB" to "Kymco",
    "RFG" to "Sanyang SYM",
    "RFL" to "Adly",
    "RFT" to "CPI",
    "RF3" to "Aeon Motor",
    "SAD" to "Jaguar (F-Pace)",
    "SAL" to "Land Rover",
    "SAJ" to "Jaguar",
    "SAR" to "Rover",
    "SB1" to "Toyota",
    "SBM" to "McLaren",
    "SCA" to "Rolls Royce",
    "SCB" to "Bentley",
    "SCC" to "Lotus Cars",
    "SCE" to "DeLorean Motor Cars N. Ireland",
    "SCF" to "Aston",
    "SDB" to "Peugeot (formerly Talbot)",
    "SED" to "General Motors Luton Plant",
    "SEY" to "LDV",
    "SFA" to "Ford",
    "SFD" to "Alexander Dennis",
    "SHH" to "Honda",
    "SHS" to "Honda",
    "SJN" to "Nissan",
    "SKF" to "Vauxhall",
    "SLP" to "JCB Research",
    "SMT" to "Triumph Motorcycles",
    "SUF" to "Fiat Auto",
    "SUL" to "FSC",
    "SUP" to "FSO-Daewoo",
    "SUU" to "Solaris Bus & Coach",
    "SWV" to "TA-NO",
    "TCC" to "Micro Compact Car AG (smart 1998-1999)",
    "TDM" to "QUANTYA Swiss Electric Movement",
    "TK9" to "SOR buses",
    "TMA" to "Hyundai Motor Manufacturing",
    "TMB" to "Škoda",
    "TMK" to "Karosa",
    "TMP" to "Škoda trolleybuses",
    "TMT" to "Tatra",
    "TM9" to "Škoda trolleybuses",
    "TNE" to "TAZ",
    "TN9" to "Karosa",
    "TRA" to "Ikarus Bus",
    "TRU" to "Audi",
    "TSE" to "Ikarus Egyedi Autobuszgyar",
    "TSM" to "Suzuki",
    "TW1" to "Toyota Caetano",
    "TYA" to "Mitsubishi Trucks",
    "TYB" to "Mitsubishi Trucks",
    "UU1" to "Renault Dacia",
    "UU3" to "ARO",
    "UU6" to "Daewoo",
    "U5Y" to "Kia Motors",
    "U6Y" to "Kia Motors",
    "VAG" to "Magna Steyr Puch",
    "VAN" to "MAN",
    "VBK" to "KTM (Motorcycles)",
    "VF1" to "Renault",
    "VF2" to "Renault",
    "VF3" to "Peugeot",
    "VF4" to "Talbot",
    "VF6" to "Renault (Trucks & Buses)",
    "VF7" to "Citroën",
    "VF8" to "Matra",
    "VF9" to "Bugatti",
    "795" to "Bugatti",
    "VG5" to "MBK (motorcycles)",
    "VLU" to "Scania",
    "VN1" to "SOVAB",
    "VNE" to "Irisbus",
    "VNK" to "Toyota",
    "VNV" to "Renault-Nissan",
    "VSA" to "Mercedes-Benz",
    "VSE" to "Suzuki (Santana Motors)",
    "VSK" to "Nissan",
    "VSS" to "SEAT",
    "VSX" to "Opel",
    "VS6" to "Ford",
    "VS7" to "Citroën",
    "VS9" to "Carrocerias Ayats",
    "VTH" to "Derbi (motorcycles)",
    "VTL" to "Yamaha (motorcycles)",
    "VTT" to "Suzuki (motorcycles)",
    "VV9" to "TAURO",
    "VWA" to "Nissan",
    "VWV" to "Volkswagen",
    "VX1" to "Zastava / Yugo Serbia",
    "WAG" to "Neoplan",
    "WAU" to "Audi",
    "WA1" to "Audi SUV",
    "WBA" to "BMW",
    "WBS" to "BMW M",
    "WBW" to "BMW",
    "WBY" to "BMW",
    "WDA" to "Daimler",
    "WDB" to "Mercedes-Benz",
    "WDC" to "DaimlerChrysler",
    "WDD" to "Mercedes-Benz",
    "WDF" to "Mercedes-Benz (commercial vehicles)",
    "WEB" to "Evobus GmbH (Mercedes-Bus)",
    "WJM" to "Iveco Magirus",
    "WF0" to "Ford",
    "WKE" to "Fahrzeugwerk Bernard Krone GmbH & Co. KG",
    "WKK" to "Kässbohrer/Setra",
    "WMA" to "MAN",
    "WME" to "smart",
    "WMW" to "MINI",
    "WMX" to "Mercedes-AMG",
    "WP0" to "Porsche",
    "WP1" to "Porsche SUV",
    "W09" to "RUF",
    "W0L" to "Opel",
    "W0V" to "Opel",
    "WUA" to "quattro GmbH",
    "WVG" to "Volkswagen MPV/SUV",
    "WVW" to "Volkswagen",
    "WV1" to "Volkswagen Commercial Vehicles",
    "WV2" to "Volkswagen Bus/Van",
    "WV3" to "Volkswagen Trucks",
    "XLB" to "Volvo (NedCar)",
    "XLE" to "Scania",
    "XLR" to "DAF (trucks)",
    "XL9" to "Spyker",
    "363" to "Spyker",
    "XMC" to "Mitsubishi (NedCar)",
    "XTA" to "Lada/AvtoVAZ",
    "XTC" to "KAMAZ",
    "XTH" to "GAZ",
    "XTT" to "UAZ/Sollers",
    "XTY" to "LiAZ",
    "XUF" to "General Motors",
    "XUU" to "AvtoTor (General Motors SKD)",
    "XW8" to "Volkswagen Group",
    "XWB" to "UZ-Daewoo",
    "XWE" to "AvtoTor (Hyundai-Kia SKD)",
    "X1M" to "PAZ",
    "X4X" to "AvtoTor (BMW SKD)",
    "X7L" to "Renault AvtoFramos",
    "X7M" to "Hyundai TagAZ",
    "YBW" to "Volkswagen",
    "YB1" to "Volvo Trucks",
    "YCM" to "Mazda",
    "YE2" to "Van Hool (buses)",
    "YH2" to "BRP (Lynx snowmobiles)",
    "YK1" to "Saab-Valmet",
    "YS2" to "Scania AB",
    "YS3" to "Saab",
    "YS4" to "Scania Bus",
    "YTN" to "Saab NEVS",
    "YT9" to "Koenigsegg",
    "007" to "Koenigsegg",
    "034" to "Carvia",
    "YU7" to "Husaberg (motorcycles)",
    "YV1" to "Volvo Cars",
    "YV4" to "Volvo Cars",
    "YV2" to "Volvo Trucks",
    "YV3" to "Volvo Buses",
    "Y3M" to "MAZ",
    "Y6D" to "Zaporozhets/AvtoZAZ",
    "ZAA" to "Autobianchi",
    "ZAM" to "Maserati",
    "ZAP" to "Piaggio/Vespa/Gilera",
    "ZAR" to "Alfa Romeo",
    "ZBN" to "Benelli",
    "ZCG" to "Cagiva SpA / MV Agusta",
    "ZCF" to "Iveco",
    "ZDM" to "Ducati Motor Holdings SpA",
    "ZDF" to "Ferrari Dino",
    "ZD0" to "Yamaha",
    "ZD3" to "Beta Motor",
    "ZD4" to "Aprilia",
    "ZFA" to "Fiat",
    "ZFC" to "Fiat V.I.",
    "ZFF" to "Ferrari",
    "ZGU" to "Moto Guzzi",
    "ZHW" to "Lamborghini",
    "ZJM" to "Malaguti",
    "ZJN" to "Innocenti",
    "ZKH" to "Husqvarna Motorcycles",
    "ZLA" to "Lancia",
    "ZOM" to "OM",
    "Z8M" to "Marussia",
    "1B3" to "Dodge",
    "1C3" to "Chrysler",
    "1C4" to "Chrysler",
    "1C6" to "Chrysler",
    "1D3" to "Dodge",
    "1FA" to "Ford Motor Company",
    "1FB" to "Ford Motor Company",
    "1FC" to "Ford Motor Company",
    "1FD" to "Ford Motor Company",
    "1FM" to "Ford Motor Company",
    "1FT" to "Ford Motor Company",
    "1FU" to "Freightliner",
    "1FV" to "Freightliner",
    "1F9" to "FWD Corp.",
    "1G" to "General Motors",
    "1GC" to "Chevrolet Truck",
    "1GT" to "GMC Truck",
    "1G1" to "Chevrolet",
    "1G2" to "Pontiac",
    "1G3" to "Oldsmobile",
    "1G4" to "Buick",
    "1G6" to "Cadillac",
    "1G8" to "Saturn",
    "1GM" to "Pontiac",
    "1GY" to "Cadillac",
    "1H" to "Honda",
    "1HD" to "Harley-Davidson",
    "1J4" to "Jeep",
    "1J8" to "Jeep",
    "1L" to "Lincoln",
    "1ME" to "Mercury",
    "1M1" to "Mack Truck",
    "1M2" to "Mack Truck",
    "1M3" to "Mack Truck",
    "1M4" to "Mack Truck",
    "1M9" to "Mynatt Truck & Equipment",
    "1N" to "Nissan",
    "1NX" to "NUMMI",
    "1P3" to "Plymouth",
    "1R9" to "Roadrunner Hay Squeeze",
    "1VW" to "Volkswagen",
    "1XK" to "Kenworth",
    "1XP" to "Peterbilt",
    "1YV" to "Mazda (AutoAlliance International)",
    "1ZV" to "Ford (AutoAlliance International)",
    "2A4" to "Chrysler",
    "2BP" to "Bombardier Recreational Products",
    "2B3" to "Dodge",
    "2B7" to "Dodge",
    "2C3" to "Chrysler",
    "2CN" to "CAMI",
    "2D3" to "Dodge",
    "2FA" to "Ford Motor Company",
    "2FB" to "Ford Motor Company",
    "2FC" to "Ford Motor Company",
    "2FM" to "Ford Motor Company",
    "2FT" to "Ford Motor Company",
    "2FU" to "Freightliner",
    "2FV" to "Freightliner",
    "2FZ" to "Sterling",
    "2Gx" to "General Motors",
    "2G1" to "Chevrolet",
    "2G2" to "Pontiac",
    "2G3" to "Oldsmobile",
    "2G4" to "Buick",
    "2G9" to "Gnome Homes",
    "2HG" to "Honda",
    "2HK" to "Honda",
    "2HJ" to "Honda",
    "2HM" to "Hyundai",
    "2M" to "Mercury",
    "2NV" to "Nova Bus",
    "2P3" to "Plymouth",
    "2T" to "Toyota",
    "2TP" to "Triple E LTD",
    "2V4" to "Volkswagen",
    "2V8" to "Volkswagen",
    "2WK" to "Western Star",
    "2WL" to "Western Star",
    "2WM" to "Western Star",
    "3C4" to "Chrysler",
    "3D3" to "Dodge",
    "3D4" to "Dodge",
    "3FA" to "Ford Motor Company",
    "3FE" to "Ford Motor Company",
    "3G" to "General Motors",
    "3H" to "Honda",
    "3JB" to "BRP (all-terrain vehicles)",
    "3MD" to "Mazda",
    "3MZ" to "Mazda",
    "3N" to "Nissan",
    "3P3" to "Plymouth",
    "3VW" to "Volkswagen",
    "4F" to "Mazda",
    "4JG" to "Mercedes-Benz",
    "4M" to "Mercury",
    "4RK" to "Nova Bus",
    "4S" to "Subaru-Isuzu Automotive",
    "4T" to "Toyota",
    "4T9" to "Lumen Motors",
    "4UF" to "Arctic Cat Inc.",
    "4US" to "BMW",
    "4UZ" to "Frt-Thomas Bus",
    "4V1" to "Volvo",
    "4V2" to "Volvo",
    "4V3" to "Volvo",
    "4V4" to "Volvo",
    "4V5" to "Volvo",
    "4V6" to "Volvo",
    "4VL" to "Volvo",
    "4VM" to "Volvo",
    "4VZ" to "Volvo",
    "538" to "Zero Motorcycles",
    "5F" to "Honda Alabama",
    "5J" to "Honda Ohio",
    "5L" to "Lincoln",
    "5N1" to "Nissan",
    "5NP" to "Hyundai",
    "5T" to "Toyota - trucks",
    "5YJ" to "Tesla, Inc.",
    "6AB" to "MAN",
    "6F4" to "Nissan Motor Company",
    "6F5" to "Kenworth",
    "6FP" to "Ford Motor Company",
    "6G1" to "General Motors-Holden (post Nov 2002)",
    "6G2" to "Pontiac (GTO & G8)",
    "6H8" to "General Motors-Holden (pre Nov 2002)",
    "6MM" to "Mitsubishi Motors",
    "6T1" to "Toyota Motor Corporation",
    "6U9" to "Privately Imported car",
    "8AD" to "Peugeot",
    "8AF" to "Ford Motor Company",
    "8AG" to "Chevrolet",
    "8AJ" to "Toyota",
    "8AK" to "Suzuki",
    "8AP" to "Fiat",
    "8AW" to "Volkswagen",
    "8A1" to "Renault",
    "8GD" to "Peugeot",
    "8GG" to "Chevrolet",
    "935" to "Citroën",
    "936" to "Peugeot",
    "93H" to "Honda",
    "93R" to "Toyota",
    "93U" to "Audi",
    "93V" to "Audi",
    "93X" to "Mitsubishi Motors",
    "93Y" to "Renault",
    "94D" to "Nissan",
    "9BD" to "Fiat",
    "9BF" to "Ford Motor Company",
    "9BG" to "Chevrolet",
    "9BM" to "Mercedes-Benz",
    "9BR" to "Toyota",
    "9BS" to "Scania",
    "9BW" to "Volkswagen",
    "9FB" to "Renault",
    "WB1" to "BMW Motorrad of North America",
)